using Heimdall.Core.Dtos;
using Heimdall.Core.Models;
using Mapster;

namespace Heimdall.BLL.Mapping;

/// <summary>
/// Strongly-typed Mapster mapper between <see cref="Ticket"/> entities and
/// <see cref="TicketDto"/> view models.
/// </summary>
/// <remarks>
/// The implementation (<c>Mappers/TicketMapper.cs</c>) is initially generated by the
/// <c>Mapster.Tool</c> CLI from the declarations on this interface plus the
/// <see cref="TicketMappingRegister"/> configuration, then lightly hand-tuned (see the
/// header of that file). Regenerate after changing either by running
/// <c>dotnet dotnet-mapster mapper -a
/// src/Heimdall.BLL/bin/Debug/net10.0/Heimdall.BLL.dll -o
/// src/Heimdall.BLL/Mappers -N true</c> from the repo root, then re-apply the documented
/// post-generation tweaks before committing.
/// </remarks>
[Mapper]
public interface ITicketMapper
{
    /// <summary>Maps a domain <see cref="Ticket"/> to its <see cref="TicketDto"/> projection.</summary>
    TicketDto Map(Ticket source);

    /// <summary>
    /// Maps a <see cref="TicketDto"/> to a domain <see cref="Ticket"/>.
    /// <c>DateCreated</c> and <c>DateUpdated</c> are intentionally not mapped — see
    /// <see cref="TicketMappingRegister"/>.
    /// </summary>
    Ticket Map(TicketDto source);

    /// <summary>Maps a sequence of <see cref="Ticket"/> entities to <see cref="TicketDto"/>s.</summary>
    IReadOnlyList<TicketDto> Map(IReadOnlyList<Ticket> source);
}
