// <auto-generated source="Mapster.Tool" hand-edited="true">
//     Initially generated by `dotnet dotnet-mapster mapper -a Heimdall.BLL.dll -o
//     src/Heimdall.BLL/Mappers -N true` from <see cref="ITicketMapper"/> and
//     <see cref="TicketMappingRegister"/>, then hand-tuned to:
//       1. Throw <see cref="ArgumentNullException"/> on null inputs (matching the
//          non-nullable <see cref="ITicketMapper"/> contract) instead of silently
//          returning <see langword="null"/>.
//       2. Use a concrete <see cref="System.Collections.Generic.List{T}"/> with a
//          <see langword="foreach"/> loop in the list mapper, removing the
//          intermediate <see cref="System.Collections.Generic.IReadOnlyList{T}"/>
//          assignment and <see cref="System.Collections.Generic.ICollection{T}"/>
//          downcast emitted by the tool, and ensuring the enumerator is disposed.
//
//     If you regenerate this file, re-apply the two tweaks above before committing.
// </auto-generated>

using System;
using System.Collections.Generic;
using Heimdall.Core.Dtos;
using Heimdall.Core.Models;

namespace Heimdall.BLL.Mapping;

public partial class TicketMapper : ITicketMapper
{
    public TicketDto Map(Ticket source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return new TicketDto
        {
            Id = source.Id,
            Title = source.Title,
            Description = source.Description,
            Status = source.Status,
            Priority = source.Priority,
            Reporter = source.Reporter,
            Assignee = source.Assignee,
            DateCreated = source.DateCreated,
            DateUpdated = source.DateUpdated,
        };
    }

    public Ticket Map(TicketDto source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return new Ticket
        {
            Id = source.Id,
            Title = source.Title,
            Description = source.Description,
            Status = source.Status,
            Priority = source.Priority,
            Reporter = source.Reporter,
            Assignee = source.Assignee,
        };
    }

    public IReadOnlyList<TicketDto> Map(IReadOnlyList<Ticket> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        var result = new List<TicketDto>(source.Count);
        foreach (var item in source)
        {
            result.Add(Map(item));
        }
        return result;
    }
}
