using System;
using Autofac;
using Heimdall.BLL.Mapping;
using Heimdall.BLL.Services;
using Heimdall.Core.Interfaces;
using Heimdall.DAL.Caching;
using Heimdall.DAL.Repositories;

namespace Heimdall.Web.DependencyInjection;

/// <summary>
/// Registers the BLL, DAL, and Mapster components into the Autofac container.
/// </summary>
public class ApplicationModule : Autofac.Module
{
    /// <inheritdoc />
    protected override void Load(ContainerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        // Repositories
        builder
            .RegisterType<TicketRepository>()
            .As<ITicketRepository>()
            .InstancePerLifetimeScope();

        // Caching
        builder.RegisterType<RedisCacheService>().As<ICacheService>().SingleInstance();

        // Services
        builder.RegisterType<TicketService>().As<ITicketService>().InstancePerLifetimeScope();

        // Mapster — the TicketMapper implementation is source-generated by Mapster.Tool
        // (see Mappers/TicketMapper.g.cs) from the [Mapper] interface in
        // Mapping/ITicketMapper.cs. The generated mapper is stateless and thread-safe,
        // so we register it as a singleton.
        builder.RegisterType<TicketMapper>().As<ITicketMapper>().SingleInstance();
    }
}
