using System;
using Autofac;
using Heimdall.BLL.Authorization;
using Heimdall.BLL.Authorization.OpenFga;
using Heimdall.BLL.Enrollment;
using Heimdall.BLL.Mapping;
using Heimdall.BLL.Services;
using Heimdall.BLL.Tokens;
using Heimdall.Core.Interfaces;
using Heimdall.DAL.Caching;
using Heimdall.DAL.Repositories;
using Microsoft.Extensions.Configuration;

namespace Heimdall.Web.DependencyInjection;

/// <summary>
/// Registers the BLL, DAL, and Mapster components into the Autofac container.
/// </summary>
public class ApplicationModule : Autofac.Module
{
    /// <inheritdoc />
    protected override void Load(ContainerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        // Repositories
        builder
            .RegisterType<TicketRepository>()
            .As<ITicketRepository>()
            .InstancePerLifetimeScope();

        // Caching
        builder.RegisterType<RedisCacheService>().As<ICacheService>().SingleInstance();

        // Phase 5.5 step 11 — access-token denylist sitting on the same Redis
        // multiplexer as the cache. Stateless (it pulls IDatabase from the
        // multiplexer per call) so SingleInstance is correct and matches the
        // lifetime of the multiplexer itself.
        builder
            .RegisterType<RedisAccessTokenDenylist>()
            .As<IAccessTokenDenylist>()
            .SingleInstance();

        // Services
        builder.RegisterType<TicketService>().As<ITicketService>().InstancePerLifetimeScope();

        // Phase 3.6 step 11 — admin tuple-management surface. Routes admin
        // membership Add/Remove through the existing ITupleWriter seam so the
        // OpenFGA failure-mode contract (log + audit + swallow + backfill
        // reconcile) is preserved end-to-end.
        builder
            .RegisterType<MembershipAdminService>()
            .As<IMembershipAdminService>()
            .InstancePerLifetimeScope();

        // Mapster — the TicketMapper implementation is source-generated by Mapster.Tool
        // (see Mappers/TicketMapper.cs) from the [Mapper] interface in
        // Mapping/ITicketMapper.cs. The generated mapper is stateless and thread-safe,
        // so we register it as a singleton.
        builder.RegisterType<TicketMapper>().As<ITicketMapper>().SingleInstance();

        // Authorization seam — docs/proposals/team-collaboration.md §6 (Phase 2.6 step 18)
        // and docs/proposals/openfga.md §3 step 9 (Phase 3.5 cutover). All implementations
        // are registered AsSelf so the configuration-driven factory below can resolve
        // whichever one matches the Authorization:Provider flag without accidentally
        // exposing more than one as IPermissionService.
        builder
            .RegisterType<TeamRoleBackedPermissionService>()
            .AsSelf()
            .InstancePerLifetimeScope();
        builder
            .RegisterType<OpenFgaPermissionService>()
            .AsSelf()
            .InstancePerLifetimeScope();
        builder
            .RegisterType<NotImplementedPermissionService>()
            .AsSelf()
            .InstancePerLifetimeScope();

        // Bind IPermissionService against the configured provider. Default = "TeamRole"
        // (Phase 2 behaviour); "OpenFga" → OpenFgaPermissionService (Phase 3.5,
        // openfga.md §3 step 9) which routes every check through the FGA Check seam.
        // Any other value is treated as a misconfiguration and bound to the
        // not-implemented service so a typo fails loudly at the first authorization
        // call instead of silently allowing or denying actions.
        builder
            .Register(componentContext =>
            {
                IConfiguration configuration = componentContext.Resolve<IConfiguration>();
                string? provider = configuration["Authorization:Provider"];

                if (string.IsNullOrWhiteSpace(provider)
                    || string.Equals(provider, "TeamRole", StringComparison.OrdinalIgnoreCase))
                {
                    return (IPermissionService)componentContext.Resolve<TeamRoleBackedPermissionService>();
                }

                if (string.Equals(provider, "OpenFga", StringComparison.OrdinalIgnoreCase))
                {
                    return componentContext.Resolve<OpenFgaPermissionService>();
                }

                return componentContext.Resolve<NotImplementedPermissionService>();
            })
            .As<IPermissionService>()
            .InstancePerLifetimeScope();

        // User enrollment seam — docs/proposals/team-collaboration.md §8 (Phase 2.9 step 26).
        // Captured now as an interface so the eventual implementations
        // (AdminInviteEnrollmentService for admin-driven invites, LdapEnrollmentService
        // for directory-backed onboarding) drop into the same shape without churning
        // every call site. No caller in Phase 2 consumes this seam — it is bound to a
        // fail-loud not-implemented service so any premature integration surfaces
        // immediately as a NotImplementedException at the call site, instead of
        // silently fabricating a user or no-op'ing. Swap this registration when the
        // first real implementation ships.
        builder
            .RegisterType<NotImplementedEnrollmentService>()
            .As<IUserEnrollmentService>()
            .InstancePerLifetimeScope();

        // OpenFGA — Phase 3.3 + 3.4 of docs/proposals/openfga.md. All OpenFGA
        // services (SDK client, IOpenFgaAuthorizationService, ITupleWriter,
        // OpenFgaBackfillJob, IMemoryCache, IOptions<OpenFgaOptions>) are
        // registered via OpenFgaServiceCollectionExtensions.AddHeimdallOpenFga(...)
        // on the MEL service collection in Program.cs and forwarded into Autofac
        // by AutofacServiceProviderFactory. When OPENFGA_API_URL is unset, the
        // extension registers no-op fall-backs so dev/test stacks can boot
        // without a sidecar.
    }
}
